"""Add playlist functionality to Schedule model

Revision ID: 080ce83ae317
Revises: 9b10f1b6f56f
Create Date: 2025-10-28 20:12:05.143592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080ce83ae317'
down_revision = '9b10f1b6f56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns for playlist functionality
    op.add_column('schedule', sa.Column('schedule_type', sa.String(length=20), nullable=True))
    op.add_column('schedule', sa.Column('folder_path', sa.String(length=500), nullable=True))
    op.add_column('schedule', sa.Column('playlist_duration', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('track_interval', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('max_tracks', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('shuffle_mode', sa.Boolean(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE schedule SET schedule_type = 'single_file' WHERE schedule_type IS NULL")
    op.execute("UPDATE schedule SET track_interval = 10 WHERE track_interval IS NULL")
    op.execute("UPDATE schedule SET shuffle_mode = 1 WHERE shuffle_mode IS NULL")
    
    # Note: SQLite doesn't support ALTER COLUMN, so we skip the filename nullable change
    # Existing schedules will still have filename as required, new playlist schedules will have it as null
    
    # Create foreign key if it doesn't exist (may already exist from previous migrations)
    try:
        op.create_foreign_key(None, 'schedule', 'schedule_list', ['schedule_list_id'], ['id'])
    except:
        pass  # Foreign key might already exist
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, 'schedule', type_='foreignkey')
    except:
        pass  # Constraint might not exist
    
    # Note: Skipping filename nullable revert due to SQLite limitations
    op.drop_column('schedule', 'shuffle_mode')
    op.drop_column('schedule', 'max_tracks')
    op.drop_column('schedule', 'track_interval')
    op.drop_column('schedule', 'playlist_duration')
    op.drop_column('schedule', 'folder_path')
    op.drop_column('schedule', 'schedule_type')
    # ### end Alembic commands ###
