"""Add volume column to schedule

Revision ID: 43568c9cde79
Revises: e3d80371ffd1
Create Date: 2025-11-14 13:02:59.391193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43568c9cde79'
down_revision = 'e3d80371ffd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('volume')

    # ### end Alembic commands ###
