"""Add is_muted column to Schedule

Revision ID: 48e0161eee0f
Revises: bca82c185a74
Create Date: 2025-10-22 20:38:45.138734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e0161eee0f'
down_revision = 'bca82c185a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('is_muted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'is_muted')
    # ### end Alembic commands ###
